apiVersion: 1
groups:
    - orgId: 1
      name: disk-evaluation
      folder: disk-rules
      interval: 30m
      rules:
        - uid: bfd7351a-ddcf-4278-a8a9-7137d88a8525
          title: Filesystem Use
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 172800
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                expr: 100-((100/node_filesystem_size_bytes{mountpoint=~"/|/data|/mnt/backup",})*node_filesystem_avail_bytes)
                interval: ""
                intervalMs: 60000
                legendFormat: '{{mountpoint}}'
                maxDataPoints: 2000
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 85
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: hOQFB01Mk
          panelId: 5
          noDataState: NoData
          execErrState: Error
          for: 1h
          annotations:
            __dashboardUid__: hOQFB01Mk
            __panelId__: "5"
          isPaused: false
