{
 "title": "Disk Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Filesystem Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-((100/node_filesystem_size_bytes{mountpoint=~\"/|/data|/mnt/backup\",})*node_filesystem_avail_bytes)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Current Filesystem Use",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-((100/node_filesystem_size_bytes{mountpoint=~\"/|/data|/mnt/backup\",})*node_filesystem_avail_bytes)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Root Filesystem Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-((100/node_filesystem_size_bytes{mountpoint=~\"/\",})*node_filesystem_avail_bytes)",
     "legendFormat": "root fs"
    }
   ]
  },
  {
   "title": "Bcakup Filesystem Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-((100/node_filesystem_size_bytes{mountpoint=~\"/mnt/backup\",})*node_filesystem_avail_bytes)",
     "legendFormat": "backup fs"
    }
   ]
  },
  {
   "title": "Root Filesystem Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-((100/node_filesystem_size_bytes{mountpoint=~\"/data\",})*node_filesystem_avail_bytes)",
     "legendFormat": "data fs"
    }
   ]
  }
 ]
}