{
 "title": "KNX Meteo",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Outdoor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brightness",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "knx_weather_brightness_lux", "legendFormat": "Brightness LUX" }
   ]
  },
  {
   "title": "Windspeed",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "knx_weather_windspeed_kmh", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "knx_room_temperatur_C{\"roomName\" = \"Terrace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rain Indicator",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "knx_weather_rain_indicator", "legendFormat": "__auto" }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Room Temperature Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (roomName) (knx_room_temperatur_C{\"sensorName\" != \"gang-oben\", \"sensorName\" != \"weatherstation\" })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Temperatur",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(avg by (roomName) (knx_room_temperatur_C{\"sensorName\" != \"gang-oben\", \"roomName\" != \"Terrace\"}))",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "Temp Indoor/Outdoor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "knx_room_temperatur_C{sensorName=\"küche\"} or knx_room_temperatur_C{sensorName=\"weatherstation\"}",
     "legendFormat": "{{roomName}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "knx_room_humidity_percentage", "legendFormat": "{{roomName}}" }
   ]
  },
  { "title": "Windspeed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Windspeed",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    { "expr": "knx_weather_windspeed_kmh", "legendFormat": "Windspeed in km/h" }
   ]
  },
  {
   "title": "Max Windspeed",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(knx_weather_windspeed_kmh[15m])",
     "legendFormat": "15m"
    },
    {
     "expr": "max_over_time(knx_weather_windspeed_kmh[1h])",
     "legendFormat": "1h"
    },
    {
     "expr": "max_over_time(knx_weather_windspeed_kmh[8h])",
     "legendFormat": "8h"
    },
    {
     "expr": "max_over_time(knx_weather_windspeed_kmh[24h])",
     "legendFormat": "24h"
    },
    {
     "expr": "max_over_time(knx_weather_windspeed_kmh[7d])",
     "legendFormat": "7d"
    },
    {
     "expr": "max_over_time(knx_weather_windspeed_kmh[4w])",
     "legendFormat": "4w"
    },
    {
     "expr": "max_over_time(knx_weather_windspeed_kmh[26w])",
     "legendFormat": "6m"
    },
    {
     "expr": "max_over_time(knx_weather_windspeed_kmh[1y])",
     "legendFormat": "1y"
    }
   ]
  },
  {
   "title": "Avg Windspeed",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(knx_weather_windspeed_kmh[15m])",
     "legendFormat": "15m"
    },
    {
     "expr": "avg_over_time(knx_weather_windspeed_kmh[1h])",
     "legendFormat": "1h"
    },
    {
     "expr": "avg_over_time(knx_weather_windspeed_kmh[8h])",
     "legendFormat": "8h"
    },
    {
     "expr": "avg_over_time(knx_weather_windspeed_kmh[24h])",
     "legendFormat": "24h"
    },
    {
     "expr": "avg_over_time(knx_weather_windspeed_kmh[7d])",
     "legendFormat": "7d"
    },
    {
     "expr": "avg_over_time(knx_weather_windspeed_kmh[4w])",
     "legendFormat": "4w"
    },
    {
     "expr": "avg_over_time(knx_weather_windspeed_kmh[26w])",
     "legendFormat": "6m"
    },
    {
     "expr": "avg_over_time(knx_weather_windspeed_kmh[1y])",
     "legendFormat": "1y"
    }
   ]
  }
 ]
}