{
 "title": "Memory Performance",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100-((100/node_memory_MemTotal_bytes)*node_memory_MemAvailable_bytes)"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "topk(10, memory_usage)", "legendFormat": "{{process}} {{pid}}" }
   ]
  },
  {
   "title": "Memory usage in % over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (100/node_memory_MemTotal_bytes) * node_memory_MemAvailable_bytes",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Free memory in % over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100/node_memory_MemTotal_bytes) * node_memory_MemFree_bytes",
     "legendFormat": "Free Memory"
    }
   ]
  },
  {
   "title": "Memory Usage Averaged Over Time",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sum_over_time( memory_usage[$__range:1m]) / ($__range_s / 60))",
     "legendFormat": "{{process}} {{pid}}"
    }
   ]
  },
  {
   "title": "Cached memory in % over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100/node_memory_MemTotal_bytes) * node_memory_Cached_bytes",
     "legendFormat": "Cached Memory"
    }
   ]
  }
 ]
}