{
 "title": "Node Overall",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Filesystem Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-((100/node_filesystem_size_bytes{mountpoint=~\"/|/data|/mnt/backup\",})*node_filesystem_avail_bytes)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100-((100/node_memory_MemTotal_bytes)*node_memory_MemAvailable_bytes)"
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Overall CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Utilization %"
    }
   ]
  },
  {
   "title": "Filesystem Use",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100-((100/node_filesystem_size_bytes{mountpoint=~\"/|/data\",})*node_filesystem_avail_bytes)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory usage in % over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (100/node_memory_MemTotal_bytes) * node_memory_MemAvailable_bytes",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"lo|eth0\"}[1m])",
     "legendFormat": "Receive {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"lo|eth0\"}[1m])",
     "legendFormat": "Send {{device}}"
    }
   ]
  }
 ]
}