{
 "title": "Shelly Power",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(shelly_plug_power_consumption_w)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Consumption Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "shelly_plug_power_consumption_w",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "Current consumption by device",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shelly_plug_power_consumption_w",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "Total consumption by device over time",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(shelly_plug_power_consumption_w[$__range])*($__range/3600)",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "Shelly Devices Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shelly_plug_power_consumption_w",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "Shelly Devices Current",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shelly_plug_current_a", "legendFormat": "{{sensorName}}" }
   ]
  },
  {
   "title": "Shelly Devices Voltage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shelly_plug_voltage_v", "legendFormat": "{{sensorName}}" }
   ]
  },
  {
   "title": "Devices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Signal Strengt",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      { "expr": "shelly_wifi_signal", "legendFormat": "{{sensorName}}" }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      { "expr": "shelly_temperature_c", "legendFormat": "{{sensorName}}" }
     ]
    }
   ]
  }
 ]
}