version: '3.4'

services:
  prometheus:
    image: prom/prometheus:v2.23.0
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml 
      - /data/prometheus:/prometheus

  grafana:
    image: grafana/grafana:7.3.5
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana/data
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources 
        #environment:
        #- 

  pushgateway:
    image: prom/pushgateway:v1.3.0
    container_name: pushgateway
    restart: always
    ports:
      - 9091:9091
