global:
  scrape_interval:     60s # Set a high scrape_interval either globally or per-job to avoid hitting Azure Monitor API limits.
 
scrape_configs:
  - job_name: node_exporter 
    scrape_interval: 30s
    static_configs:
      - targets: ['192.168.1.137:9100','192.168.1.137:9091']
