{
 "title": "CPU Performance",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Overall CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Utilization %"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, avg_over_time(cpu_usage[$__interval]))",
     "legendFormat": "{{process}} {{pid}}"
    }
   ]
  },
  {
   "title": "CPU Utilization by CPU mode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,mode) (rate(node_cpu_seconds_total{mode=~'system|iowait|softirq|user'}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Processes over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "topk(5,cpu_usage)", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "CPU load 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Dual Core Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{cpu=~\"0|1\"}",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Load 5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load5" }
   ]
  },
  {
   "title": "Quad Core Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_cpu_frequency_hertz{cpu!~\"0|1\"}",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU load 15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_thermal_zone_temp", "legendFormat": "zone {{zone}}" }
   ]
  }
 ]
}